"use client";
import {useCallback,useEffect,useState} from "react";
import {Activity,Database,Radio,Server} from "lucide-react";
import {fetchSystemStatus,type SystemStatus} from "@/services/api";
import {PageHeader,ErrorState} from "@/components/ui/Page";
import {StatusBadge} from "@/components/ui/StatusBadge";
const icons=[Database,Server,Activity,Radio];
export function HealthWorkspace(){
 const[data,setData]=useState<SystemStatus|null>(null),[failed,setFailed]=useState(false);
 const load=useCallback(async()=>{setFailed(false);try{setData(await fetchSystemStatus())}catch{setFailed(true)}},[]);
 useEffect(()=>{void load()},[load]);
 return <main className="mx-auto max-w-[1800px] p-4 sm:p-6 xl:p-8"><PageHeader eyebrow="PLATFORM / OBSERVABILITY" title="System health" description="A concise view of the infrastructure supporting live operations."/>
 {failed?<section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/[.07] dark:bg-slate-900/70"><ErrorState onRetry={()=>void load()}/></section>:!data?<section className="grid gap-3 sm:grid-cols-2">{Array.from({length:4},(_,i)=><article className="h-36 animate-pulse rounded-2xl border border-slate-200 bg-slate-100 dark:border-white/[.06] dark:bg-white/[.025]" key={i}/>)}</section>:<><section className="grid gap-3 sm:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/[.07] dark:bg-slate-900/70"><Activity className="text-cyan-600 dark:text-cyan-300" size={20}/><div className="mt-4 text-[10px] uppercase tracking-wider text-slate-500">Platform health</div><strong className="mt-1 block text-3xl text-slate-900 dark:text-white">{data.status==="operational"?"100%":"Degraded"}</strong><div className="mt-3"><StatusBadge status={data.status} pulse/></div></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/[.07] dark:bg-slate-900/70"><Database className="text-emerald-600 dark:text-emerald-300" size={20}/><div className="mt-4 text-[10px] uppercase tracking-wider text-slate-500">Online sources</div><strong className="mt-1 block text-3xl text-slate-900 dark:text-white">{data.sources.online??0}</strong><div className="mt-3 text-xs text-slate-500 dark:text-slate-600">Live ingestion providers</div></article></section><section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-white/[.07] dark:bg-slate-900/70"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4 dark:border-white/[.06]"><h2 className="text-sm font-semibold text-slate-900 dark:text-white">Service checks</h2><StatusBadge status={data.status}/></div><div className="grid gap-px bg-slate-100 dark:bg-white/[.04] sm:grid-cols-2">{Object.entries(data.checks).map(([name,status],i)=>{const Icon=icons[i%icons.length];return <div key={name} className="bg-white p-5 dark:bg-slate-900"><Icon size={17} className="text-cyan-600 dark:text-cyan-300"/><div className="mt-4 text-xs font-medium text-slate-700 dark:text-slate-300">{name}</div><div className="mt-2"><StatusBadge status={status}/></div></div>})}</div></section></>}</main>;
}
