"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Plus, Power } from "lucide-react";
import { createSource, fetchSources, updateSource } from "@/services/api";
import type { DataSource } from "@/types/tracking";
import { AdvancedDataTable, type DataColumn } from "@/components/ui/AdvancedDataTable";
import { DetailDrawer, Dialog } from "@/components/ui/Overlay";
import { PageHeader } from "@/components/ui/Page";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { Button } from "@/components/ui/Button";
import { useAuthStore } from "@/stores/auth-store";
const columns: DataColumn<DataSource>[] = [
 { id:"name", header:"Name", cell:r=><strong>{r.name}</strong>, sortValue:r=>r.name, priority:true }, { id:"type",header:"Type",cell:r=>r.type,sortValue:r=>r.type },
 { id:"status",header:"Status",cell:r=><StatusBadge status={r.status}/>,sortValue:r=>r.status }, { id:"updated",header:"Last update",cell:r=>r.last_message_at?new Date(r.last_message_at).toLocaleString():"No messages",sortValue:r=>r.last_message_at??"" },
 { id:"latency",header:"Latency",cell:r=>r.latency_ms===null?"—":`${r.latency_ms} ms`,sortValue:r=>r.latency_ms??0 }, { id:"rate",header:"Messages/min",cell:r=>Math.round(r.messages_per_minute).toLocaleString(),sortValue:r=>r.messages_per_minute }
];
type SourceForm={name:string;type:string;driver:"flightradar24"|"mock_aircraft";api_key:string};
export function SourceWorkspace(){
 const canManage=useAuthStore(s=>s.can)("sources.manage"); const [sources,setSources]=useState<DataSource[]>([]); const [selected,setSelected]=useState<DataSource|null>(null); const [create,setCreate]=useState(false); const [loading,setLoading]=useState(true); const [failed,setFailed]=useState(false); const [busy,setBusy]=useState(false); const [form,setForm]=useState<SourceForm>({name:"FlightRadar24",type:"Aviation API",driver:"flightradar24",api_key:""}); const [formError,setFormError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setFailed(false);try{setSources(await fetchSources())}catch{setFailed(true)}finally{setLoading(false)}},[]); useEffect(()=>{void load()},[load]);
 const submit=async(event:FormEvent)=>{event.preventDefault();setFormError("");if(!form.name.trim()||!form.api_key.trim()){setFormError("A source name and API key are required.");return}setBusy(true);try{const source=await createSource(form);setSources(rows=>[...rows,source]);setCreate(false);setSelected(source)}catch{setFormError("The source could not be created. Check the details and try again.")}finally{setBusy(false)}};
 const toggle=async()=>{if(!selected)return;setBusy(true);try{const source=await updateSource(selected.id,{enabled:!selected.enabled});setSelected(source);setSources(rows=>rows.map(row=>row.id===source.id?source:row))}finally{setBusy(false)}};
 return <main className="app-page"><PageHeader eyebrow="OPERATIONS / INGESTION" title="Data sources" description="Monitor the connection health and throughput of each telemetry provider." actions={canManage?<Button variant="primary" onClick={()=>setCreate(true)}><Plus/>Add source</Button>:undefined}/><AdvancedDataTable data={sources} columns={columns} isLoading={loading} error={failed} onRetry={()=>void load()} onRowClick={setSelected}/><DetailDrawer open={!!selected} onClose={()=>setSelected(null)} title="Source details">{selected&&<div className="drawer-content"><span className="detail-kicker">{selected.driver} · {selected.type}</span><h3 className="detail-title">{selected.name}</h3><StatusBadge status={selected.status}/><div className="detail-grid" style={{marginTop:18}}><div><small>Throughput</small><strong>{Math.round(selected.messages_per_minute)} msg/min</strong></div><div><small>Latency</small><strong>{selected.latency_ms??"—"} ms</strong></div><div><small>Errors</small><strong>{selected.error_count}</strong></div><div><small>Enabled</small><strong>{selected.enabled?"Yes":"No"}</strong></div></div>{canManage&&<div className="form-actions"><Button disabled={busy} onClick={()=>void toggle()}><Power/>{selected.enabled?"Disable source":"Enable source"}</Button></div>}</div>}</DetailDrawer><Dialog open={create} onClose={()=>setCreate(false)} title="Add data source" description="Connect an approved telemetry provider to your workspace."><form onSubmit={submit}><label className="form-field"><span>Source name</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label className="form-field"><span>Provider</span><select value={form.driver} onChange={e=>setForm({...form,driver:e.target.value as SourceForm["driver"],type:e.target.value==="flightradar24"?"Aviation API":"Mock aircraft"})}><option value="flightradar24">FlightRadar24</option><option value="mock_aircraft">Mock aircraft feed</option></select></label><label className="form-field"><span>Official API key</span><input type="password" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})} required/></label>{form.driver==="flightradar24"&&<p className="source-note">FlightRadar24 stays offline until its official API mapping is enabled on the ingestion worker.</p>}{formError&&<p className="form-error">{formError}</p>}<div className="form-actions"><Button type="button" onClick={()=>setCreate(false)}>Cancel</Button><Button type="submit" variant="primary" disabled={busy}>{busy?"Creating…":"Create source"}</Button></div></form></Dialog></main>;
}
