"use client";
import Link from "next/link";
import {Activity,Database,Maximize2,Minimize2,RadioTower,ShieldAlert,Wifi} from "lucide-react";
import {useState} from "react";
import {OperationsMap} from "@/components/map/OperationsMap";
import {AuthGate} from "@/components/auth/AuthGate";
import {OperationsDrawer} from "@/components/navigation/OperationsDrawer";
import {useDashboardController} from "@/controllers/useDashboardController";
import {PageHeader} from "@/components/ui/Page";

function SecuredDashboard(){const dashboard=useDashboardController(),[fullscreen,setFullscreen]=useState(false);const telemetry=dashboard.sources.reduce((sum,source)=>sum+source.messages_per_minute,0);const stats=[{label:"Active tracks",value:dashboard.metrics.tracks,detail:"in monitored airspace",trend:"Live",icon:RadioTower},{label:"Data sources",value:dashboard.sources.length,detail:`${dashboard.metrics.sources} reporting`,trend:"Operational",icon:Wifi},{label:"Active alerts",value:dashboard.metrics.alerts,detail:"require operator review",trend:dashboard.metrics.alerts?"Review":"Clear",icon:ShieldAlert},{label:"Telemetry rate",value:Math.round(telemetry),detail:"messages per minute",trend:"Nominal",icon:Database}];return <OperationsDrawer><main className="app-page"><PageHeader eyebrow="OPERATIONS / OVERVIEW" title="Command overview" description="Live multi-source situational awareness and system activity."/><section className="kpi-grid">{stats.map(({label,value,detail,trend,icon:Icon})=><article className="panel stat-card" key={label}><Icon/><small>{label}</small><strong>{value}</strong><footer><span>{detail}</span><b>{trend}</b></footer></article>)}</section><section className="overview-grid"><section className={`panel overview-map ${fullscreen?"map-fullscreen":""}`}><button className="map-fullscreen-toggle" onClick={()=>setFullscreen(value=>!value)} aria-label={fullscreen?"Exit full screen map":"Open full screen map"}>{fullscreen?<Minimize2/>:<Maximize2/>}</button><div className="map-stage"><OperationsMap/><div className="map-heading"><span>LIVE THEATER</span><strong>New York Airspace</strong><small><i/> Streaming telemetry</small></div></div></section><aside className="panel activity-panel"><div className="panel-heading"><h2>Priority activity</h2><Link href="/alerts">View alerts</Link></div>{dashboard.alerts.slice(0,5).map(alert=><article className="activity-item" key={alert.id}><strong>{alert.title}</strong><p>{alert.message??"No additional context available."}</p><span className={`status-badge status-badge--${alert.severity==="critical"?"danger":"warning"}`}><i/>{alert.severity}</span></article>)}{dashboard.alerts.length===0&&<p className="empty-state">No active alerts. The operation is quiet.</p>}</aside></section></main></OperationsDrawer>}
export function DashboardShell(){return <AuthGate><SecuredDashboard/></AuthGate>}
