"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Plus,Shield,Trash2,UserCog,X} from "lucide-react";
import {createOrganizationUser,deleteOrganizationUser,fetchOrganizationUsers,updateOrganizationUser} from "@/services/api";
import type {OrganizationUser,Role} from "@/types/auth";
import {useAuthStore} from "@/stores/auth-store";
import {Button} from "@/components/ui/Button";

const roles:Role[]=["administrator","supervisor","operator","viewer"];
const roleHelp:Record<Role,string>={administrator:"Full access, including user and source administration.",supervisor:"Manage operations, alerts, geofences and layouts.",operator:"Monitor tracks and respond to operational alerts.",viewer:"Read-only situational awareness."};
type Draft={name:string;email:string;password:string;role:Role};const empty:Draft={name:"",email:"",password:"",role:"viewer"};

export function UserManager(){
 const current=useAuthStore(s=>s.user);const[users,setUsers]=useState<OrganizationUser[]>([]),[draft,setDraft]=useState<Draft>(empty),[editing,setEditing]=useState<OrganizationUser|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setUsers(await fetchOrganizationUsers())}catch{setError("Unable to load organization users.")}},[]);
 useEffect(()=>{void load()},[load]);
 const showCreate=()=>{setEditing(null);setDraft(empty);setError("");setOpen(true)},showEdit=(u:OrganizationUser)=>{setEditing(u);setDraft({name:u.name,email:u.email,password:"",role:u.role});setError("");setOpen(true)};
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{if(editing)await updateOrganizationUser(editing.id,{name:draft.name,email:draft.email,role:draft.role,...(draft.password?{password:draft.password}:{})});else await createOrganizationUser(draft);setOpen(false);await load()}catch{setError("Could not save this user. Check the fields and try again.")}finally{setBusy(false)}};
 const remove=async(u:OrganizationUser)=>{if(!confirm(`Remove ${u.name} from this organization?`))return;try{await deleteOrganizationUser(u.id);await load()}catch{setError("This account could not be removed.")}};
 return <main className="mx-auto max-w-[1400px] p-4 sm:p-6 xl:p-8"><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-300">Access control</span><h1 className="mt-2 text-3xl font-semibold text-white">User & role manager</h1><p className="mt-2 text-sm text-slate-500">{current?.organization?.name}</p></div><Button variant="primary" onClick={showCreate}><Plus size={16}/>Add user</Button></div>
 <section className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{roles.map((role,i)=><article key={role} className="rounded-2xl border border-white/[.07] bg-slate-900/70 p-4" style={{animationDelay:`${i*60}ms`}}><div className="flex items-start justify-between"><Shield size={17} className="text-cyan-300"/><strong className="text-xl text-white">{users.filter(u=>u.role===role).length}</strong></div><div className="mt-4 text-xs font-semibold capitalize text-slate-200">{role}</div><p className="mt-1 text-[11px] leading-5 text-slate-600">{roleHelp[role]}</p></article>)}</section>
 {error&&<div className="mb-4 rounded-xl border border-rose-400/15 bg-rose-400/5 p-3 text-xs text-rose-300">{error}</div>}
 <section className="overflow-hidden rounded-2xl border border-white/[.07] bg-slate-900/70"><div className="flex items-center gap-3 border-b border-white/[.06] px-5 py-4"><UserCog size={18} className="text-cyan-300"/><div><h2 className="text-sm font-semibold text-white">Organization users</h2><p className="text-[10px] text-slate-600">{users.length} active account{users.length===1?"":"s"}</p></div></div><div className="overflow-x-auto"><div className="min-w-[720px]"><div className="grid grid-cols-[2fr_1fr_1fr_1fr] border-b border-white/[.05] px-5 py-3 text-[9px] font-bold uppercase tracking-[.16em] text-slate-600"><span>Operator</span><span>Role</span><span>Created</span><span>Actions</span></div>{users.map(u=><div key={u.id} className="grid grid-cols-[2fr_1fr_1fr_1fr] items-center border-b border-white/[.04] px-5 py-3.5 last:border-0 hover:bg-white/[.02]"><span className="flex items-center gap-3"><i className="grid h-9 w-9 place-items-center rounded-full bg-cyan-300/10 text-[10px] font-bold text-cyan-300 not-italic">{u.name.slice(0,2).toUpperCase()}</i><span><strong className="block text-sm text-slate-200">{u.name}</strong><small className="text-[10px] text-slate-600">{u.email}</small></span></span><span className="text-[10px] font-semibold uppercase tracking-wider text-cyan-300">{u.role}</span><span className="text-xs text-slate-500">{new Date(u.created_at).toLocaleDateString()}</span><span className="flex gap-2"><Button size="sm" onClick={()=>showEdit(u)}>Edit</Button><Button size="sm" variant="danger" disabled={u.id===current?.id} onClick={()=>void remove(u)}><Trash2 size={14}/></Button></span></div>)}</div></div></section>
 {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4 backdrop-blur-md" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><form onSubmit={submit} className="relative w-full max-w-lg rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"><button type="button" onClick={()=>setOpen(false)} className="absolute right-4 top-4 text-slate-500 hover:text-white"><X size={18}/></button><span className="text-[9px] font-bold uppercase tracking-[.2em] text-cyan-300">{editing?"Edit account":"New account"}</span><h2 className="mt-2 text-xl font-semibold text-white">{editing?editing.name:"Add organization user"}</h2><div className="mt-6 space-y-4">{[["Full name","text",draft.name,(v:string)=>setDraft({...draft,name:v})],["Email","email",draft.email,(v:string)=>setDraft({...draft,email:v})]].map(([label,type,value,onChange])=><label key={label as string} className="block"><span className="mb-1.5 block text-xs text-slate-400">{label as string}</span><input className="h-10 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-sm outline-none focus:border-cyan-300/40" type={type as string} required value={value as string} onChange={e=>(onChange as (v:string)=>void)(e.target.value)}/></label>)}<label className="block"><span className="mb-1.5 block text-xs text-slate-400">{editing?"New password (optional)":"Temporary password"}</span><input className="h-10 w-full rounded-xl border border-white/10 bg-slate-950/60 px-3 text-sm outline-none focus:border-cyan-300/40" type="password" required={!editing} minLength={10} value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})}/></label><label className="block"><span className="mb-1.5 block text-xs text-slate-400">Role</span><select className="h-10 w-full rounded-xl border border-white/10 bg-slate-950 px-3 text-sm outline-none" value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value as Role})}>{roles.map(role=><option key={role}>{role}</option>)}</select><small className="mt-1 block text-[10px] text-slate-600">{roleHelp[draft.role]}</small></label></div><Button type="submit" variant="primary" disabled={busy} className="mt-6 w-full">{busy?"Saving…":"Save account"}</Button></form></div>}
 </main>;
}
